name: Tune

on:
  push:
    branches:
      - tune

jobs:
  linux:
    env:
      COMPILER: clang++
      COMP: clang
      ARCH: x86-64-avx512
      SDE: /home/runner/work/Pikafish/Pikafish/.output/sde-temp-files/sde-external-9.27.0-2023-09-13-lin/sde -future --
    defaults:
      run:
        working-directory: src
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: make
        run: make clean && make -j build && make strip

      - name: upload to fishtest
        run: curl https://test.pikafish.org/api/pre_upload -F file=@pikafish -F "file_type=engine" -F "password=${{ secrets.NOTHING }}"

      - name: Download SDE package
        uses: petarpetrovt/setup-sde@91a1a03434384e064706634125a15f7446d2aafb  # @v2.3
        with:
          environmentVariableName: SDE_DIR
          sdeVersion: 9.27.0

      - name: print variables table
        run: printf 'quit' | $SDE ./pikafish